/* SK Movies anime episode UI. Copyrighted/pirated streams are not embedded. Add only authorized video URLs in EPISODE_SOURCES. */
(function(){
  const CONFIG={
    'Naruto':{count:220},
    'Naruto: Shippuden':{count:500},
    'One Piece':{count:1171},
    'Demon Slayer: Kimetsu no Yaiba':{count:55},
    'Jujutsu Kaisen':{count:47},
    'Death Note':{count:37},
    'Hunter x Hunter':{count:148}
  };
  /* Put authorized/embed video URLs here, e.g. EPISODE_SOURCES.Naruto[1] = 'https://...'; */
  const EPISODE_SOURCES={};
  const posterMap={'Naruto':'https://image.tmdb.org/t/p/w500/mLoI2Zto2JYUvSB8PpqvZIV7vWj.jpg','Naruto: Shippuden':'https://image.tmdb.org/t/p/w500/qOxedwaJzdms2alAmIEHEnDeDzg.jpg','Demon Slayer: Kimetsu no Yaiba':'https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg'};
  function ensureStyles(){if(document.getElementById('anime-player-style'))return;const s=document.createElement('style');s.id='anime-player-style';s.textContent=`.anime-poster{width:100%;aspect-ratio:2/3;display:flex;align-items:center;justify-content:center;background:#120d18;color:#fff;font-size:52px;overflow:hidden}.anime-poster img{width:100%;height:100%;object-fit:cover;display:block}.episode-modal{display:none;position:fixed;inset:0;z-index:5000;background:rgba(0,0,0,.88);padding:14px;align-items:center;justify-content:center}.episode-modal.show{display:flex}.episode-box{width:min(820px,100%);max-height:92vh;overflow:auto;background:#111;border:1px solid #333;border-radius:18px;padding:18px;position:relative}.episode-box h2{font-size:22px;margin:0 45px 5px 0}.episode-box p{color:#aaa;font-size:13px;margin:0 0 14px}.episode-close{position:absolute;right:12px;top:10px;border:0;background:#252525;color:#fff;border-radius:50%;width:38px;height:38px;font-size:24px;cursor:pointer}.episode-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px}.episode-btn{border:1px solid #333;background:#1b1b1b;color:#fff;border-radius:9px;padding:10px 4px;font-weight:800;cursor:pointer}.episode-btn:hover{border-color:#e50914;background:#262626}.episode-player{display:none;margin:0 0 16px;background:#000;border-radius:12px;overflow:hidden}.episode-player.show{display:block}.episode-player iframe,.episode-player video{display:block;width:100%;aspect-ratio:16/9;border:0;background:#000}.episode-message{padding:18px;text-align:center;background:#181818;border-radius:12px;color:#aaa}.episode-message strong{display:block;color:#fff;margin-bottom:6px}@media(max-width:520px){.episode-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.episode-box{padding:14px}.episode-btn{padding:9px 2px;font-size:12px}}`;document.head.appendChild(s)}
  function createModal(){if(document.getElementById('episode-modal'))return document.getElementById('episode-modal');const m=document.createElement('div');m.id='episode-modal';m.className='episode-modal';m.innerHTML='<div class="episode-box"><button class="episode-close" type="button">×</button><h2 id="episode-title">Episodes</h2><p id="episode-subtitle"></p><div id="episode-player" class="episode-player"></div><div id="episode-message" class="episode-message"><strong>Select an episode</strong><span>The video player will appear here when an authorized video source is configured.</span></div><div id="episode-grid" class="episode-grid"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.episode-close'))m.classList.remove('show')});return m}
  function play(title,n){const src=EPISODE_SOURCES[title]?.[n];const p=document.getElementById('episode-player'),msg=document.getElementById('episode-message');p.innerHTML='';p.classList.remove('show');if(!src){msg.style.display='block';msg.innerHTML='<strong>Episode '+n+'</strong><span>No authorized video source has been configured for this episode yet.</span>';return}msg.style.display='none';const iframe=document.createElement('iframe');iframe.src=src;iframe.allow='autoplay; fullscreen; picture-in-picture';iframe.allowFullscreen=true;p.appendChild(iframe);p.classList.add('show')}
  function openModal(title){const c=CONFIG[title];if(!c)return;const m=createModal();document.getElementById('episode-title').textContent=title+' — Episodes';document.getElementById('episode-subtitle').textContent='Episodes 1–'+c.count;const grid=document.getElementById('episode-grid');grid.innerHTML='';for(let i=1;i<=c.count;i++){const b=document.createElement('button');b.type='button';b.className='episode-btn';b.textContent='Episode '+i;b.onclick=()=>play(title,i);grid.appendChild(b)}m.classList.add('show');}
  function decorate(){document.querySelectorAll('.card').forEach(card=>{const title=card.querySelector('h3')?.textContent?.trim();if(!CONFIG[title]||card.dataset.animeReady)return;card.dataset.animeReady='1';const old=card.querySelector('.anime-poster');if(old&&posterMap[title])old.innerHTML='<img loading="lazy" src="'+posterMap[title]+'" alt="'+title.replace(/"/g,'')+' poster">';const row=card.querySelector('.btn-row');if(!row)return;const watch=row.querySelector('.watch-btn');if(watch){watch.removeAttribute('href');watch.removeAttribute('target');watch.textContent='▶ Episodes';watch.href='#';watch.addEventListener('click',e=>{e.preventDefault();openModal(title)})}const free=document.createElement('button');free.type='button';free.className='free-watch-btn';free.textContent='🆓 Free';free.addEventListener('click',()=>openModal(title));row.appendChild(free)})}
  ensureStyles();setTimeout(decorate,300);setTimeout(decorate,1500);setInterval(decorate,3000);
})();
