/* SK Movies — legal/open cartoon & animation collection */
(function(){
  const cartoons=[
    {title:'Big Buck Bunny',emoji:'🐰',source:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',license:'Creative Commons'},
    {title:'Sintel',emoji:'🐉',source:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',license:'Creative Commons'},
    {title:'Elephants Dream',emoji:'🐘',source:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',license:'Creative Commons'},
    {title:'For Bigger Blazes',emoji:'🔥',source:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',license:'Open sample video'},
    {title:'For Bigger Escapes',emoji:'🚗',source:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',license:'Open sample video'},
    {title:'For Bigger Fun',emoji:'🎈',source:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',license:'Open sample video'}
  ];
  function style(){if(document.getElementById('sk-cartoon-style'))return;const s=document.createElement('style');s.id='sk-cartoon-style';s.textContent='.sk-cartoon-section{margin:42px 0}.sk-cartoon-head{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}.sk-cartoon-head h2{margin:4px 0}.sk-cartoon-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.sk-cartoon-card{background:#151515;border:1px solid #292929;border-radius:16px;overflow:hidden}.sk-cartoon-art{height:190px;display:grid;place-items:center;font-size:68px;background:radial-gradient(circle,#3b1010,#090909)}.sk-cartoon-body{padding:15px}.sk-cartoon-body h3{margin:0 0 6px}.sk-cartoon-body p{font-size:12px;opacity:.65}.sk-cartoon-watch{width:100%;padding:11px;border:0;border-radius:9px;background:#e50914;color:#fff;font-weight:800}.sk-cartoon-player{position:fixed;inset:0;background:#000d;display:none;align-items:center;justify-content:center;padding:14px;z-index:99998}.sk-cartoon-player.show{display:flex}.sk-cartoon-box{width:min(960px,100%);background:#111;border-radius:16px;padding:16px;position:relative}.sk-cartoon-box h2{color:#fff;margin:0 50px 12px 0}.sk-cartoon-box video{width:100%;aspect-ratio:16/9;background:#000;border-radius:10px}.sk-cartoon-close{position:absolute;right:14px;top:10px;width:44px;height:44px;border:0;border-radius:50%;background:#292929;color:#fff;font-size:28px}@media(max-width:700px){.sk-cartoon-grid{grid-template-columns:1fr}.sk-cartoon-head{display:block}}';document.head.appendChild(s)}
  function player(){let p=document.getElementById('sk-cartoon-player');if(p)return p;p=document.createElement('div');p.id='sk-cartoon-player';p.className='sk-cartoon-player';p.innerHTML='<div class="sk-cartoon-box"><button class="sk-cartoon-close">×</button><h2 id="sk-cartoon-title">Now Playing</h2><video id="sk-cartoon-video" controls playsinline preload="metadata"></video></div>';document.body.appendChild(p);p.querySelector('.sk-cartoon-close').onclick=()=>{const v=p.querySelector('video');v.pause();v.removeAttribute('src');v.load();p.classList.remove('show')};return p}
  function init(){style();if(document.getElementById('sk-cartoon-section'))return;const main=document.querySelector('main');if(!main)return;const sec=document.createElement('section');sec.id='sk-cartoon-section';sec.className='sk-cartoon-section';sec.innerHTML='<div class="sk-cartoon-head"><div><span class="eyebrow">FREE • LEGAL • ANIMATION</span><h2>🎨 Cartoons & Animation</h2></div><span>6 titles</span></div><div class="sk-cartoon-grid"></div>';const grid=sec.querySelector('.sk-cartoon-grid');cartoons.forEach(c=>{const a=document.createElement('article');a.className='sk-cartoon-card';a.innerHTML='<div class="sk-cartoon-art">'+c.emoji+'</div><div class="sk-cartoon-body"><h3>'+c.title+'</h3><p>'+c.license+'</p><button class="sk-cartoon-watch">▶ Watch Now</button></div>';a.querySelector('button').onclick=()=>{const p=player(),v=p.querySelector('video');p.querySelector('#sk-cartoon-title').textContent='▶ '+c.title;v.src=c.source;p.classList.add('show');v.play().catch(()=>{})};grid.appendChild(a)});main.appendChild(sec)}
  [300,1200,3000].forEach(t=>setTimeout(init,t));
})();
