/* SK Movies: legal/open movies played through official Blender Video embeds. */
(function(){
  const legalMovies=[
    ['Big Buck Bunny','pAQiVCgv2CsLg79KKXUoMw','Creative Commons • Blender Foundation','🐰'],
    ['Sintel','2PcJe5aZqozRvH7MJ8BTmC','Creative Commons • Blender Foundation','🐉'],
    ['Tears of Steel','hs1zJY8mdr3iH2JNmxpeGV','Creative Commons • Blender Foundation','🤖'],
    ['Spring','8B5QmoLSS3mWJ4fmZZu3Ye','Creative Commons • Blender Foundation','🌲']
  ];
  const esc=s=>String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  function css(){
    if(document.getElementById('sk-embed-style'))return;
    const s=document.createElement('style');s.id='sk-embed-style';s.textContent='#sk-legal-section{margin:28px 0 50px}.sk-legal-head{display:flex;justify-content:space-between;align-items:end;gap:16px;margin-bottom:16px}.sk-legal-head h2{margin:4px 0;font-size:28px}.sk-legal-head p{opacity:.65}.sk-legal-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.sk-legal-card{background:#151515;border:1px solid #292929;border-radius:16px;overflow:hidden;box-shadow:0 8px 30px #0005}.sk-legal-art{height:190px;display:grid;place-items:center;background:radial-gradient(circle,#3a0808,#0b0b0b);font-size:74px}.sk-legal-art span{position:absolute;margin-top:135px;font-size:11px;font-weight:800;letter-spacing:2px;color:#ff2222}.sk-legal-body{padding:14px}.sk-legal-body h3{margin:0 0 7px;font-size:17px}.sk-legal-meta{font-size:12px;opacity:.65;min-height:30px}.sk-legal-watch{width:100%;border:0;border-radius:9px;padding:11px;background:#12a957;color:white;font-weight:800;cursor:pointer}.sk-legal-player{position:fixed;inset:0;background:#000c;display:none;align-items:center;justify-content:center;padding:16px;z-index:99999}.sk-legal-player.show{display:flex}.sk-legal-box{position:relative;width:min(920px,100%);background:#111;border:1px solid #3a3a3a;border-radius:18px;padding:18px;box-shadow:0 20px 80px #000}.sk-legal-box h2{margin:0 50px 14px 0;color:#fff}.sk-legal-close{position:absolute;right:18px;top:14px;width:46px;height:46px;border:0;border-radius:50%;background:#292929;color:#fff;font-size:30px;cursor:pointer}.sk-legal-frame{width:100%;aspect-ratio:16/9;border:0;border-radius:12px;background:#000;display:block}.sk-legal-credit{font-size:12px;opacity:.65;margin:12px 0 0;color:#fff}@media(max-width:900px){.sk-legal-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.sk-legal-head{display:block}.sk-legal-grid{grid-template-columns:1fr}.sk-legal-art{height:220px}.sk-legal-box{padding:12px}.sk-legal-close{right:12px;top:8px}}';document.head.appendChild(s)}
  function player(){let p=document.getElementById('sk-legal-player');if(p)return p;p=document.createElement('div');p.id='sk-legal-player';p.className='sk-legal-player';p.innerHTML='<div class="sk-legal-box"><button class="sk-legal-close" type="button" aria-label="Close">×</button><h2 id="sk-legal-title">Now Playing</h2><iframe id="sk-legal-frame" class="sk-legal-frame" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe><p class="sk-legal-credit">Official Blender Video • Open/Creative Commons movie.</p></div>';document.body.appendChild(p);const close=()=>{document.getElementById('sk-legal-frame').src='about:blank';p.classList.remove('show')};p.querySelector('.sk-legal-close').onclick=close;p.addEventListener('click',e=>{if(e.target===p)close()});return p}
  function play(movie){const p=player();document.getElementById('sk-legal-title').textContent='▶ '+movie[0];p.classList.add('show');document.getElementById('sk-legal-frame').src='https://video.blender.org/videos/embed/'+movie[1]}
  function init(){css();const grid=document.querySelector('.movies');if(!grid)return;if(!document.getElementById('sk-legal-section')){const section=document.createElement('section');section.id='sk-legal-section';section.className='sk-legal-section';section.innerHTML='<div class="sk-legal-head"><div><span class="eyebrow">FREE • LEGAL • OPEN MOVIES</span><h2>🎬 Watch Free Movies</h2><p>Official Blender open movies • play here</p></div><span>4 titles</span></div><div class="sk-legal-grid"></div>';const cards=section.querySelector('.sk-legal-grid');legalMovies.forEach(movie=>{const card=document.createElement('article');card.className='sk-legal-card';card.innerHTML='<div class="sk-legal-art"><div>'+movie[3]+'</div><span>OPEN MOVIE</span></div><div class="sk-legal-body"><h3>'+esc(movie[0])+'</h3><p class="sk-legal-meta">'+esc(movie[2])+'</p><button class="sk-legal-watch" type="button">▶ Watch Now</button></div>';card.querySelector('button').onclick=()=>play(movie);cards.appendChild(card)});grid.parentElement.insertBefore(section,grid)}}
  setTimeout(init,300);setTimeout(init,1200);setTimeout(init,3000);setTimeout(init,5000);
})();
