/* SK Movies: one-tap in-page playback for official/open movies. */
(function(){
  const legalMovies=[
    {title:'Big Buck Bunny',kind:'mp4',src:'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',fallback:'YE7VzlLtp-4',credit:'Blender Foundation • Creative Commons Attribution'},
    {title:'Sintel',kind:'youtube',src:'eRsGyueVLvQ',credit:'Blender Foundation • Creative Commons Attribution 3.0'},
    {title:'Tears of Steel',kind:'youtube',src:'41hv2tW5Lc4',credit:'Blender Foundation • Creative Commons Attribution 3.0'},
    {title:'Cosmos Laundromat',kind:'youtube',src:'Y-rmzh0PI3c',credit:'Blender Studio • Open Movie'},
    {title:'Spring',kind:'youtube',src:'WhWc3b3KhnY',credit:'Blender Studio • Open Movie'},
    {title:'Coffee Run',kind:'youtube',src:'PVGeM40dABA',credit:'Blender Studio • Open Movie'},
    {title:'CHARGE',kind:'youtube',src:'UXqq0ZvbOnk',credit:'Blender Studio • Open Movie'},
    {title:'WING IT!',kind:'youtube',src:'u9lj-c29dxI',credit:'Blender Studio • Open Movie'}
  ];
  const esc=s=>String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  function addCSS(){if(document.getElementById('sk-direct-style'))return;const s=document.createElement('style');s.id='sk-direct-style';s.textContent=`#sk-legal-section{margin:34px 0 54px}.sk-legal-head{display:flex;justify-content:space-between;align-items:end;gap:16px;margin-bottom:18px}.sk-legal-head h2{margin:4px 0;font-size:28px}.sk-legal-head p{opacity:.65}.sk-legal-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.sk-legal-card{background:#151515;border:1px solid #292929;border-radius:16px;overflow:hidden;box-shadow:0 8px 30px #0005;cursor:pointer;transition:.18s}.sk-legal-card:hover{transform:translateY(-3px);border-color:#e50914}.sk-legal-art{height:180px;display:grid;place-items:center;background:radial-gradient(circle,#3a0808,#0b0b0b);font-size:58px;position:relative}.sk-legal-art span{position:absolute;bottom:14px;font-size:10px;font-weight:900;letter-spacing:2px;color:#ff3333}.sk-legal-body{padding:14px}.sk-legal-body h3{margin:0 0 7px;font-size:17px}.sk-legal-meta{font-size:12px;opacity:.65;min-height:32px}.sk-direct-btn{width:100%;border:0;border-radius:9px;padding:11px;background:#e50914;color:#fff;font-weight:800;cursor:pointer}.sk-direct-btn:active{transform:scale(.98)}.sk-legal-player{position:fixed;inset:0;background:rgba(0,0,0,.94);display:none;align-items:center;justify-content:center;padding:12px;z-index:99999}.sk-legal-player.show{display:flex}.sk-legal-box{position:relative;width:min(1000px,100%);background:#111;border:1px solid #3a3a3a;border-radius:18px;padding:14px;box-shadow:0 20px 80px #000}.sk-legal-box h2{margin:0 55px 12px 0;color:#fff;font-size:21px}.sk-legal-close{position:absolute;right:12px;top:9px;width:44px;height:44px;border:0;border-radius:50%;background:#292929;color:#fff;font-size:29px;cursor:pointer}.sk-legal-media{width:100%;aspect-ratio:16/9;border:0;border-radius:12px;background:#000;display:block}.sk-legal-credit{font-size:12px;opacity:.65;margin:10px 0 0;color:#fff}.sk-legal-status{display:none;margin-top:9px;padding:9px;border-radius:9px;background:#2a1515;color:#ffb4b4;font-size:12px}.sk-legal-status.show{display:block}@media(max-width:900px){.sk-legal-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.sk-legal-head{display:block}.sk-legal-grid{grid-template-columns:1fr}.sk-legal-art{height:210px}.sk-legal-box{padding:10px}.sk-legal-close{right:9px;top:6px}}`;document.head.appendChild(s)}
  function getPlayer(){let p=document.getElementById('sk-legal-player');if(p)return p;p=document.createElement('div');p.id='sk-legal-player';p.className='sk-legal-player';p.innerHTML='<div class="sk-legal-box"><button class="sk-legal-close" type="button" aria-label="Close">×</button><h2 id="sk-legal-title">Now Playing</h2><div id="sk-legal-media"></div><p id="sk-legal-credit" class="sk-legal-credit"></p><div id="sk-legal-status" class="sk-legal-status"></div></div>';document.body.appendChild(p);const close=()=>{document.getElementById('sk-legal-media').innerHTML='';p.classList.remove('show')};p.querySelector('.sk-legal-close').onclick=close;p.addEventListener('click',e=>{if(e.target===p)close()});return p}
  function play(movie){const p=getPlayer(),title=document.getElementById('sk-legal-title'),media=document.getElementById('sk-legal-media'),credit=document.getElementById('sk-legal-credit'),status=document.getElementById('sk-legal-status');title.textContent='▶ '+movie.title;credit.textContent=movie.credit;status.classList.remove('show');media.innerHTML='';p.classList.add('show');
    if(movie.kind==='youtube'){
      const frame=document.createElement('iframe');frame.className='sk-legal-media';frame.src='https://www.youtube-nocookie.com/embed/'+movie.src+'?autoplay=1&mute=1&playsinline=1&rel=0&modestbranding=1';frame.title=movie.title;frame.allow='autoplay; fullscreen; picture-in-picture';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';media.appendChild(frame);
    }else{
      const v=document.createElement('video');v.className='sk-legal-media';v.controls=true;v.playsInline=true;v.autoplay=true;v.muted=true;v.preload='auto';v.src=movie.src;media.appendChild(v);v.play().catch(()=>{});v.addEventListener('error',()=>{media.innerHTML='<iframe class="sk-legal-media" src="https://www.youtube-nocookie.com/embed/'+movie.fallback+'?autoplay=1&mute=1&playsinline=1&rel=0&modestbranding=1" title="'+esc(movie.title)+'" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>';status.textContent='Direct source unavailable, switched automatically to the official fallback player.';status.classList.add('show')},{once:true});
    }
  }
  function init(){addCSS();const grid=document.querySelector('.movies');if(!grid||document.getElementById('sk-legal-section'))return;const section=document.createElement('section');section.id='sk-legal-section';section.innerHTML='<div class="sk-legal-head"><div><span class="eyebrow">FREE • LEGAL • OPEN MOVIES</span><h2>🎬 Watch Free Movies</h2><p>Tap any movie once — it opens and starts playing here.</p></div><span>8 titles</span></div><div class="sk-legal-grid"></div>';const cards=section.querySelector('.sk-legal-grid');const icons=['🐰','🐉','🤖','🐑','🌿','☕','⚡','✈️'];legalMovies.forEach((movie,i)=>{const card=document.createElement('article');card.className='sk-legal-card';card.tabIndex=0;card.innerHTML='<div class="sk-legal-art"><div>'+icons[i]+'</div><span>OPEN MOVIE</span></div><div class="sk-legal-body"><h3>'+esc(movie.title)+'</h3><p class="sk-legal-meta">'+esc(movie.credit)+'</p><button class="sk-direct-btn" type="button">▶ Watch Direct</button></div>';const open=()=>play(movie);card.onclick=e=>{if(e.target.tagName!=='BUTTON')open()};card.querySelector('button').onclick=open;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}};cards.appendChild(card)});grid.parentElement.insertBefore(section,grid)}
  [300,1000,2500,5000].forEach(t=>setTimeout(init,t));
})();